AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/initializers/devise.rb'
    - 'db/seeds.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
